### PR TITLE
use bash exclusively

### PR DESCRIPTION
**Pull request by anuragkhare**
Works better when fish is set as iTerm2’s login shell

### CODE REVIEW

**Comment by wouterdebie** [comment]
You forgot to remove `@shell = ENV["SHELL"] || "/usr/bin/env bash"`

**Comment by anuragkhare** [comment]
Thanks for catching that.

**Comment by wouterdebie** [comment]
Thanks! I didn't realize when the initial commit came in, but we're using bash here to just spawn the ssh sessions. You can run a different shell on remote hosts though.

**Comment by anuragkhare** [comment]
All good. It seems safer to default to bash. I'm using fish shell & it rejects constructs like '&&'.

**Pull request merged**
