### PR TITLE
Added support for iTerm 2.9

### LINKED ISSUE #40: Latest iTerm changes applescript support, breaks i2cssh
Hello,

The latest iTerm releases are breaking i2cssh due to changing the way applescript is being supported and defined. New documentation can be found: https://www.iterm2.com/applescript.html. Should make the process of splitting/etc a whole lot simpler

### PR DESCRIPTION
**Pull request by dancannon**
Updated i2cssh to support the new iTerm beta, this change is not backwards compatible and probably not 100% complete but it works. Fixes #40.

### CODE REVIEW

**Comment by lensen** [comment]
Thanks for this. I almost rolled iTerm back to stable channel..

**Comment by wouterdebie** [comment]
Sorry to get back so incredibly late on this PR. I'll merge this when 2.9 is not a test release anymore.

**Comment by wouterdebie** [comment]
Can you verify that this works for iTerm2 3? I would like to get this out as soon as it's out of beta.

Thanks!

**Comment by wouterdebie** [comment]
Actually there seems to be a complete reimplementation of appscript: https://iterm2.com/applescript.html. We might want to use this for iterm2 3.0

**Comment by dancannon** [comment]
My PR actually uses the new applescript implementation. It has been a while since I updated iTerm so ill just update and test that everything still works and get back to you.

**Comment by dancannon** [comment]
I have run a couple of tests with Build 2.9.20160206 and couldnt find any issues, although I think it would be good to test it on other machines before merging.

**Comment by wouterdebie** [comment]
@dancannon awesome! What do you think, release this or wait for iTerm2 3.0 to come out of beta? Also, can you rebase on master?

**Comment by wouterdebie** [comment]
I tested it myself and it seems to work well. Thanks! I haven't released this feature yet, because I don't want to break peoples i2cssh when they install it while not being on the iTerm2 testing version.

**Comment by wouterdebie** [comment]
Ok, screw it :) I just released version 2.0 that is iTerm2 >= 2.9 compatible and updated the README with instructions on how to install for versions < 2.9.

**Pull request merged**
