### PR TITLE
hide UNUSED window #35

### PR DESCRIPTION
**Pull request by sepich**
Fix for:
Do not show "UNUSED" window #35

### CODE REVIEW

**Comment by sanear** [comment]
Good change, yes please.

**Comment by nynhex** [comment]
Can this be merged to upstream?  I would greatly benefit from this and a new gem cut.

**Comment by dx7** [comment]
I think it could be optional. Some people could prefer the UNUSED window.

**Comment by sepich** [comment]
Screw it, i've made lighter version via new Python-API
https://github.com/sepich/iterm2-cssh

**Pull request closed without merging**
